### PR TITLE
Use signature based token for code and refresh tokens

### PR DESCRIPTION
**Pull request by bonustrack**

### CODE REVIEW

**Comment by AschContract** [comment]
o'ooo

**Comment by AschContract** [comment]
/api/auth2/token

**Comment by AschContract** [comment]
How to get token validation to pass?

**Comment by AschContract** [comment]
api/oauth2/token

**Comment by bonustrack** [comment]
@AschContract please add an issue if you have some trouble or come in our discord https://discord.gg/v52akSX for live help

**Pull request merged**
